INSERT INTO `Libros` (`isbn`, `titulo`, `autor`, `fecha`, `precio`) VALUES ('1AB', 'Java', 'cecilio', '2020-01-01', '3')
INSERT INTO `Libros` (`isbn`, `titulo`, `autor`, `fecha`, `precio`) VALUES ('2AC', 'Java Web', 'cecilio', '2020-01-02', '3')
INSERT INTO `Libros` (`isbn`, `titulo`, `autor`, `fecha`, `precio`) VALUES ('3BC', 'html', 'gema', '2020-01-02', '2')
INSERT INTO `Libros` (`isbn`, `titulo`, `autor`, `fecha`, `precio`) VALUES ('4BD', 'html5', 'andres', '2020-01-02', '2')
INSERT INTO `Libros` (`isbn`, `titulo`, `autor`, `fecha`, `precio`) VALUES ('5BD', 'C', 'maria', '2020-01-02', '5')
INSERT INTO `Libros` (`isbn`, `titulo`, `autor`, `fecha`, `precio`) VALUES ('6FG', 'PHP', null, '2020-03-02', '4')
